### PR TITLE
Some more quick changes

### PR DESCRIPTION
**Pull request by coltonfitzgerald**
BTW: I'm pretty new to Github and i'm not sure how to remove what I did with the variable declarations, but I did  fix a few things.
- Losslessly compressed all breach images
- Some more CSS Shorthand
- Removed duplicate rel attributes in the HTML

How do I remove the variable changes?

### CODE REVIEW

**Comment by spolu** [comment]
That'd be awesome if you could clean up your commit history. 

You can check the cherrypick command.

**Comment by spolu** [comment]
@rockincolton do you need any help cleaning up that history?

**Comment by coltonfitzgerald** [comment]
@spolu Yeah haha. I'm currently going through Treehouse's Github course so I don't totally understand what I'm doing yet.

**Comment by spolu** [comment]
OK!

**Pull request closed without merging**
