### PR TITLE
Issue #32 Use signature instead of hashing for auto-update

### PR DESCRIPTION
**Pull request by deian**

### CODE REVIEW

**Comment by spolu** [comment]
LGTM. Cf issue #32
Can you add the proper key where needed in the keyring so that I can give it a try?

**Comment by deian** [comment]
Both the breach and your keys are in the keyring actually.

**Comment by spolu** [comment]
Ok! Didn't see it with the one line diff! Mea culpa

**Comment by deian** [comment]
No trouble :) Let me know if you run into trouble!

**Comment by spolu** [comment]
@deian hey I've pushed some modifications on the local `auto-update-sig` branch:
https://github.com/breach/breach_core/compare/auto-update-sig?expand=1
(use `update.signature` as signature URL + add signature generation to the release creation process).

Can you have a look and tell me what you think. I'll test it live with the update server tomorrow and will merge if ok with you?

**Comment by spolu** [comment]
I fixed the branch it's now clean you can use the link above to review the changes

**Comment by deian** [comment]
LGMT

**Pull request closed without merging**
