### PR TITLE
Fix tables, 'out' to 'debug'

### PR DESCRIPTION
**Pull request by knownasilya**
No more using one table as three tables. Also changed the 'out' link to read 'debug', since it wasn't very obvious what it was.

### CODE REVIEW

**Comment by spolu** [comment]
So keeping one table is important to have a uniform layout and have buttons aligned across sections.
As far as out to debug we can call it `output` if your prefer, but `debug` is probably misleading.

Can you update your PR?

**Comment by knownasilya** [comment]
How would you like the tables? You can still have them separate tables, but have the same sized/number of columns.

**Comment by spolu** [comment]
Always better to let the browser do the layouting, no?
Fixed sizes will lead to a bunch of issues

**Comment by knownasilya** [comment]
@spolu not referring to fixed sizes. Using colgroup and colspan for the tables to say there are this many columns and they take up _n_ of _m_ space.

**Comment by knownasilya** [comment]
BTW, what's the best way to test this? Would I need to build breach and install breach_core?

**Comment by spolu** [comment]
The columns would still be disaligned across sections

**Comment by spolu** [comment]
Have a look to: https://github.com/breach/breach_core/wiki/Building-Breach-from-Source

Section 3 you can use the binary distributions of the ExoBrowser

**Comment by knownasilya** [comment]
@spolu Thanks!  

What about using percentage widths? I think that might be the ticket. 

But really we will probably have to go away from tables eventually, since we are doing just a little more then displaying tabular data. This seems like work for a responsive grid..

**Comment by spolu** [comment]
Sure you can come up with a more complex design but that's not the spirit. There's an effort right now to build a better module manager as a module here: https://github.com/mblarsen/breach-module-manager

**Comment by spolu** [comment]
Closing for now as this is not top priority + previous comment.
Opening the API for the breach-module-manager project is probably more important ATM

**Comment by knownasilya** [comment]
:smile:

**Pull request closed without merging**
