### PR TITLE
Basically nitpicked and made all the variables at the top into one declaration :)

### PR DESCRIPTION
**Pull request by coltonfitzgerald**

### CODE REVIEW

**Comment by morganrallen** [comment]
+1 (but at least it wasn't leading commas)

On Tue, Oct 7, 2014 at 4:46 PM, Colton Fitzgerald notifications@github.com
wrote:

> ---
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/rockincolton/breach_core master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/breach/breach_core/pull/209
> Commit Summary
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Update core_controls.js
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> - Changed variables into one long declaration
> 
> File Changes
> - _M_ lib/auto_updater.js
>   https://github.com/breach/breach_core/pull/209/files#diff-0 (25)
> - _M_ lib/common.js
>   https://github.com/breach/breach_core/pull/209/files#diff-1 (6)
> - _M_ lib/core_controls.js
>   https://github.com/breach/breach_core/pull/209/files#diff-2 (10)
> - _M_ lib/core_cookies.js
>   https://github.com/breach/breach_core/pull/209/files#diff-3 (6)
> - _M_ lib/core_module.js
>   https://github.com/breach/breach_core/pull/209/files#diff-4 (6)
> - _M_ lib/core_store.js
>   https://github.com/breach/breach_core/pull/209/files#diff-5 (8)
> - _M_ lib/core_tabs.js
>   https://github.com/breach/breach_core/pull/209/files#diff-6 (6)
> - _M_ lib/core_ui.js
>   https://github.com/breach/breach_core/pull/209/files#diff-7 (14)
> - _M_ lib/module_manager.js
>   https://github.com/breach/breach_core/pull/209/files#diff-8 (29)
> - _M_ lib/session.js
>   https://github.com/breach/breach_core/pull/209/files#diff-9 (13)
> - _M_ lib/session_manager.js
>   https://github.com/breach/breach_core/pull/209/files#diff-10 (9)
> 
> Patch Links:
> - https://github.com/breach/breach_core/pull/209.patch
> - https://github.com/breach/breach_core/pull/209.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/breach/breach_core/pull/209.

## 

http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by spolu** [comment]
This is really cosmetic. What's the rationale va the current form?

**Comment by coltonfitzgerald** [comment]
It's less characters total in the document xD

**Comment by morganrallen** [comment]
OH, I read that patch wrong. Leave the var variable = 1;

Its clearer, it copy/pastes better, it substitutes better, and document
sizes doesn't matter.

On Wed, Oct 8, 2014 at 10:37 AM, Colton Fitzgerald <notifications@github.com

> wrote:
> 
> It's less characters total in the document xD
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/breach/breach_core/pull/209#issuecomment-58396110.

## 

http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by spolu** [comment]
I agree. I'm not a big fan

**Comment by coltonfitzgerald** [comment]
The thing is though, JSLint picks it up as an issue. Apparently it says that all variables should be defined in one. I mean, obviously it's not a big deal but it's fun to contribute anyways :)

**Comment by morganrallen** [comment]
Are you sure that is not your settings? Because that is terrible if that is
their default.

On Wed, Oct 8, 2014 at 3:45 PM, Colton Fitzgerald notifications@github.com
wrote:

> The thing is though, JSLint picks it up as an issue. Apparently it says
> that all variables should be defined in one. I mean, obviously it's not a
> big deal but it's fun to contribute anyways :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/breach/breach_core/pull/209#issuecomment-58440127.

## 

http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by spolu** [comment]
We all agree to close it?

@rockincolton if you want to keep contributing, you could be super useful on this:
https://github.com/breach/exo_shell/issues/161

We need to write some libraries. Any language you master other than JS?

**Pull request closed without merging**
